'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("NeptuneUtility.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select rTrim([S].[IDCUST]) + &apos; - &apos; +rtrim([NAMECUST]) from [dbo].[ARCUS] [S]
        '''inner JOIN [dbo].[ARCUSO] [SO2] on [SO2].[IDCUST]=[S].[IDCUST] and [SO2].OPTFIELD=&apos;WATER&apos;
        '''where IDGRP=&apos;UT&apos; and SWACTV=1 
        '''and 
        '''(
        '''[S].[IDCUST] not in (Select IDCUST from [dbo].[ARCUSO] where OPTFIELD=&apos;METER&apos; and VALUE&lt;&gt;&apos;&apos;) 
        '''or
        '''[S].[IDCUST] not in (Select IDCUST from [dbo].[ARCUSO] where OPTFIELD=&apos;CURREAD&apos; and VALUE&lt;&gt;&apos;&apos;) 
        '''or
        '''[S].[IDCUST] not in (Select IDCUST from [dbo].[ARCUSO] where OPTFIELD=&apos;PREREAD&apos; and VALUE&lt;&gt;&apos;&apos;) 
        '''or
        '''[ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CheckMetersRecords() As String
            Get
                Return ResourceManager.GetString("CheckMetersRecords", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property CheckMissingItems() As String
            Get
                Return ResourceManager.GetString("CheckMissingItems", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[METEREDSELECTED]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[METEREDSELECTED];
        '''
        '''create table [MNP].[dbo].[METEREDSELECTED] 
        '''(
        '''[IDCUST] [char](12),
        ''').
        '''</summary>
        Friend ReadOnly Property CreateMeteredErrors() As String
            Get
                Return ResourceManager.GetString("CreateMeteredErrors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[METERED]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[METERED];
        '''
        '''create table [MNP].[dbo].[METERED] 
        '''(
        '''[IDCUST] [char](12),
        '''[OLDACC] [varchar](20),
        '''[METER] varchar(13) not null,
        '''[ACTREAD] [decimal](9, 0),
        '''[PREREAD] [decimal](9, 0),
        '''[DATEREAD] varchar(6),
        '''[TIMEREAD] varchar(6),
        '''[MONTH] tinyint,
        '''[YEAR] smallint,
        '''[WATER] [varchar](20) DEFAULT N&apos;&apos;,
        '''[GARBAGE] [varchar](20) DEFAULT N&apos;&apos;,
        '''[COMMENT] varchar(500) DEFAULT &apos;&apos;,
        '''[INTEREST] char(1) DEFAULT &apos;Y&apos;,
        '''[BALANCE] [deci [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateMeteredImportTable() As String
            Get
                Return ResourceManager.GetString("CreateMeteredImportTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[METEREDSELECTED]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[METEREDSELECTED];
        '''
        '''create table [MNP].[dbo].[METEREDSELECTED] 
        '''(
        '''[IDCUST] [char](12),
        ''').
        '''</summary>
        Friend ReadOnly Property CreateMeteredSelected() As String
            Get
                Return ResourceManager.GetString("CreateMeteredSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[PENALTYOTHERS]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[PENALTYOTHERS];
        '''
        '''create table [MNP].[dbo].[PENALTYOTHERS] 
        '''(
        '''[IDCUST] [char](12)
        ''').
        '''</summary>
        Friend ReadOnly Property CreatePenaltyOthers() As String
            Get
                Return ResourceManager.GetString("CreatePenaltyOthers", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[TRUCKEDBAD]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[TRUCKEDBAD];
        '''
        '''create table [MNP].[dbo].[TRUCKEDBAD] 
        '''(
        '''[IDCUST] [char](12),
        '''[OLDACC] [varchar](20),
        '''[CONSUMPTION] [decimal](9, 0),
        '''[MONTH] tinyint,
        '''[YEAR] smallint,
        '''[WATER] [varchar](20) DEFAULT N&apos;&apos;,
        '''[GARBAGE] [varchar](20) DEFAULT N&apos;&apos;,
        '''[COMMENT] varchar(500) DEFAULT &apos;&apos;,
        '''[AUDTDATE] date DEFAULT GETDATE()
        ''').
        '''</summary>
        Friend ReadOnly Property CreateTruckedError() As String
            Get
                Return ResourceManager.GetString("CreateTruckedError", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IF OBJECT_ID(N&apos;[MNP].[dbo].[TRUCKED]&apos;, N&apos;U&apos;) IS NOT NULL
        '''	DROP TABLE [MNP].[dbo].[TRUCKED];
        '''
        '''create table [MNP].[dbo].[TRUCKED] 
        '''(
        '''[IDCUST] [char](12),
        '''[OLDACC] [varchar](20),
        '''[CONSUMPTION] [decimal](9, 0),
        '''[MONTH] tinyint,
        '''[YEAR] smallint,
        '''[INVDESC] varchar(50) DEFAULT N&apos;&apos;,
        '''[WATER] [varchar](20) DEFAULT N&apos;&apos;,
        '''[GARBAGE] [varchar](20) DEFAULT N&apos;&apos;,
        '''[COMMENT] varchar(500) DEFAULT &apos;&apos;,
        '''[INTEREST] char(1) DEFAULT &apos;Y&apos;,
        '''[BALANCE] [decimal](15, 4) DEFAULT 0, 
        '''[MONTHLYBALANCE] [decimal](15, 4) DEFAULT  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CreateTruckedImportFile() As String
            Get
                Return ResourceManager.GetString("CreateTruckedImportFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select 
        '''--LEFT(trim([SO1].[VALUE]) + REPLICATE(&apos; &apos;,10),10)+
        '''LEFT(&apos;1&apos; + REPLICATE(&apos; &apos;,10),10)+
        '''&apos;0000&apos;+
        '''RIGHT(&apos;000&apos;+ cast(ROW_NUMBER() OVER(ORDER BY SUBSTRING([S].TEXTSTRE4,CHARINDEX(&apos; &apos;,[S].TEXTSTRE4,1),99),
        '''	RIGHT(REPLICATE(&apos;0&apos;,10)+LEFT([S].TEXTSTRE4, PATINDEX(&apos;%[^0-9]%&apos;, [S].TEXTSTRE4 + &apos;t&apos;) - 1),10)) as nvarchar(4)) ,4)+
        '''--RIGHT(&apos;000&apos;+trim([SO2].[VALUE]),4)+
        '''&apos;00&apos;+
        '''REPLICATE(&apos; &apos;,7)+
        '''&apos;5&apos;+
        '''LEFT(trim([SO3].[VALUE]) + REPLICATE(&apos; &apos;,13),13)+
        '''REPLICATE(&apos; &apos;,26)+
        '''&apos;0&apos;+
        '''REPLICATE(&apos; &apos;,64)+
        '''&apos;EUZ&apos;+
        '''REPLI [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ExportSql() As String
            Get
                Return ResourceManager.GetString("ExportSql", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select [OLDACC] from
        '''(
        '''select &apos;Old Account Number (OLDACC):&apos; + trim([VALUE]) + &apos;  found more than once.&apos;  [OLDACC],sum(1) [BAD] from [dbo].[ARCUSO] [SO]
        '''inner join [dbo].[ARCUS] [S] on [S].[IDCUST]=[SO].[IDCUST] and [S].[IDGRP]=&apos;UT&apos; and [S].[IDCUST]&lt;&gt;[S].[IDNATACCT] 
        '''where [OPTFIELD]=&apos;OLDACC&apos; 
        '''group by [VALUE]
        ''') [B]
        '''where [B].[BAD]&gt;1.
        '''</summary>
        Friend ReadOnly Property FindDuplicateOLDACC() As String
            Get
                Return ResourceManager.GetString("FindDuplicateOLDACC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select &apos;MONTH Opt field not found&apos; where &apos;MONTH&apos; not in 
        '''(
        '''SELECT OPTFIELD
        '''  FROM [dbo].[CSOPTFH])
        '''union
        '''select &apos;YEAR Opt field not found&apos; where &apos;YEAR&apos; not in 
        '''(
        '''SELECT OPTFIELD
        '''  FROM [dbo].[CSOPTFH])
        '''union
        '''
        '''select &apos;BALANCE Opt field not found&apos; where &apos;BALANCE2&apos; not in 
        '''(
        '''SELECT OPTFIELD
        '''  FROM [dbo].[CSOPTFH])
        '''union
        '''select &apos;PCINT Opt field not found&apos; where &apos;PCINT2&apos; not in 
        '''(
        '''SELECT OPTFIELD
        '''  FROM [dbo].[CSOPTFH]).
        '''</summary>
        Friend ReadOnly Property FindMissingOptFields() As String
            Get
                Return ResourceManager.GetString("FindMissingOptFields", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''SELECT {0} [Sel]
        ''',trim([S].[IDCUST]) [IDCUST]
        '''	  ,trim([SO6].[VALUE]) [OLDACC]
        '''      ,trim([S].[NAMECUST]) [CustName]
        '''      ,trim([S].[TEXTSTRE1]) [Address1]
        '''      ,trim([S].[TEXTSTRE2]) [Address2]
        '''      ,trim([S].[TEXTSTRE4]) [Address4]
        '''      ,trim([S].[NAMECITY]) [City]
        '''      ,trim([S].[CODESTTE]) [Prov]
        '''      ,trim([S].[CODEPSTL]) [PCode]
        '''	  ,trim([SO7].[VALUE]) [Water]
        '''	  ,trim([SO8].[VALUE]) [Garbage]
        '''	  ,trim([SO3].[VALUE]) [Meter]
        ''' 
        '''from [dbo].[ARCUS] [S] 
        '''inner join [dbo].[ARCUSO] [ [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GetExportRecordToSelect() As String
            Get
                Return ResourceManager.GetString("GetExportRecordToSelect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT [IDCUST]
        '''      ,[OLDACC]
        '''      ,[METER]
        '''      ,[ACTREAD]
        '''      ,[PREREAD]
        '''      ,[DATEREAD]
        '''	  ,[MONTH]
        '''	  ,[YEAR]
        '''--	  ,month(DATEADD(month, DATEDIFF(month,0,substring([DATEREAD],1,2)+&apos;-&apos;+substring([DATEREAD],3,2)+&apos;-&apos;+substring([DATEREAD],5,2)), -1)) [MONTH]
        '''--	  ,year(DATEADD(month, DATEDIFF(month,0,substring([DATEREAD],1,2)+&apos;-&apos;+substring([DATEREAD],3,2)+&apos;-&apos;+substring([DATEREAD],5,2)), -1)) [YEAR]
        '''      ,[TIMEREAD]
        '''      ,[WATER]
        '''      ,[GARBAGE]
        '''	  ,[INTEREST]
        '''	  ,[MULTITOT]
        '''	  ,[BA [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GetMetered() As String
            Get
                Return ResourceManager.GetString("GetMetered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to declare @datemax as decimal
        '''declare @month as varchar(2)
        '''declare @year as varchar(4)
        '''select @month=&apos;{0}&apos;
        '''select @year=&apos;{1}&apos;
        '''select @datemax=CAST(REPLACE(EOMONTH(@year+&apos;-&apos;+@month+&apos;-01&apos;),&apos;-&apos;,&apos;&apos;) AS DECIMAL(9,0)) 
        '''
        '''select [IDCUST],[BALANCE],@month [MONTH],@year [YEAR]  from
        '''(
        '''select [AR].[IDCUST]
        ''',[BL].[Balance] 
        '''from [dbo].[ARCUS] [AR] 
        '''inner join
        '''(
        '''	SELECT [IDCUST], (sum([AMTINVCHC])) [Balance]
        '''	  FROM [dbo].[AROBL]
        '''	  where 
        '''	  [DATEINVC]&lt;@datemax
        '''	   
        '''	  group by [IDCUST]
        '''	 ) [BL]
        '''	 on [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property GetOtherPenalty() As String
            Get
                Return ResourceManager.GetString("GetOtherPenalty", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SELECT FORMAT(([AMTPRICE]*100), &apos;N2&apos;) FROM [dbo].[ARITD] where iditem=&apos;LATEPMT&apos;.
        '''</summary>
        Friend ReadOnly Property GetPercentageInterest() As String
            Get
                Return ResourceManager.GetString("GetPercentageInterest", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select * FROM [MNP].[dbo].[TRUCKED] where isnull([COMMENT],&apos;&apos;)=&apos;&apos;  order by [IDCUST].
        '''</summary>
        Friend ReadOnly Property GetTrucked() As String
            Get
                Return ResourceManager.GetString("GetTrucked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to declare @datemax as decimal
        '''declare @datemin as decimal
        '''--  Delete all records
        '''delete from  [MNP].[dbo].[METERED];
        '''--delete from  [MNP].[dbo].[METEREDBAD];
        '''BEGIN TRAN;
        '''
        '''	Insert into [MNP].[dbo].[METERED] 
        '''	([IDCUST]
        '''				,[OLDACC]
        '''				,[METER]
        '''				,[ACTREAD]
        '''				,[PREREAD]
        '''				,[DATEREAD]
        '''				,[TIMEREAD]
        '''			  )
        '''	VALUES
        '''	{0};
        '''
        '''	-- Update new ID
        '''	update [M]
        '''	set
        '''		[M].IDCUST=[SO].[IDCUST]
        '''	From [MNP].[dbo].[METERED] [M] 
        '''	inner join [dbo].[ARCUSO] [SO] on [SO].OPTFIELD=&apos;OLDACC&apos; and [SO] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InsertIntoMetered() As String
            Get
                Return ResourceManager.GetString("InsertIntoMetered", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to declare @datemax as decimal
        '''declare @datemin as decimal
        '''
        '''--  Delete all records
        '''delete from  [MNP].[dbo].[TRUCKED];
        '''--delete from  [MNP].[dbo].[TRUCKEDBAD];
        '''
        '''BEGIN TRAN;
        '''
        '''	Insert into [MNP].[dbo].[TRUCKED] 
        '''	([IDCUST]
        '''			   ,[OLDACC]
        '''			   ,[CONSUMPTION]
        '''			   ,[MONTH]
        '''			   ,[YEAR]
        '''			   ,[INVDESC]
        '''			  )
        '''	VALUES
        '''	{0};
        '''	-- Update new ID
        '''	update [M]
        '''	set
        '''		[M].IDCUST=[SO].[IDCUST]
        '''	From [MNP].[dbo].[TRUCKED] [M]
        '''	inner join [dbo].[ARCUSO] [SO] on [SO].OPTFIELD=&apos;OLDACC&apos; and [SO].[VALU [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property InsertIntoTrucked() As String
            Get
                Return ResourceManager.GetString("InsertIntoTrucked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete from  [MNP].[dbo].[METEREDSELECTED];
        '''BEGIN TRAN;
        '''
        '''	Insert into [MNP].[dbo].[METEREDSELECTED] 
        '''	([IDCUST])
        '''	VALUES {0};
        '''COMMIT TRAN;.
        '''</summary>
        Friend ReadOnly Property InsertMeteredSelected() As String
            Get
                Return ResourceManager.GetString("InsertMeteredSelected", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UPDATE [dbo].[ARCUSO]
        '''   SET [VALUE] ={1} 
        '''WHERE [IDCUST]=&apos;{0}&apos; and [OPTFIELD]=&apos;CURREAD&apos;;
        '''UPDATE [dbo].[ARCUSO]
        '''   SET [VALUE] ={2} 
        '''WHERE [IDCUST]=&apos;{0}&apos; and [OPTFIELD]=&apos;PREREAD&apos;;
        '''UPDATE [dbo].[ARCUSO]
        '''   SET [VALUE] =&apos;{3}&apos; 
        '''WHERE [IDCUST]=&apos;{0}&apos; and [OPTFIELD]=&apos;METER&apos;;
        '''
        '''
        '''
        '''.
        '''</summary>
        Friend ReadOnly Property UpdateMeteredUser() As String
            Get
                Return ResourceManager.GetString("UpdateMeteredUser", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
